environment          = "dev"
region               = "eu-west-1"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.3.0/24", "10.0.4.0/24"]
azs                  = ["eu-west-1a", "eu-west-1b"]
instance_type        = "t3.micro"
key_name             = "My-key"
db_instance_class    = "db.t3.micro"
db_name              = "myapp"
db_username          = "admin"
asg_min_size         = 1
asg_max_size         = 3
asg_desired_capacity = 2
